### ISSUE TITLE
Error when select components are used in arrays.

### ISSUE THREAD

**Issue by JFrankfurt** [networknt/react-schema-form#117]
![image](https://user-images.githubusercontent.com/5773490/45972301-6534d500-c009-11e8-94e5-c647310ff51d.png)

I'm not tracking exactly what's going on here, but I think it might have something to do with this change: https://github.com/networknt/react-schema-form/commit/d3227aeb6295e9404324b7211a773030aaafd38f
It surfaces here: https://github.com/networknt/react-schema-form/blob/master/src/Select.js#L31

The error can be solved by giving the `Select` an optional default value of `''`, but I think there might be a deeper problem here so I wanted to get input from @dogada and @stevehu.

If you select an option for a `Select` component it will retain the placeholder when it loses focus.
![arrayselect](https://user-images.githubusercontent.com/5773490/45982367-88ba4880-c026-11e8-88b0-c0855c8e3912.gif)

**Comment by JFrankfurt** [comment]
Similar error for `TextFields` in arrays:
![image](https://user-images.githubusercontent.com/5773490/45975934-623ee200-c013-11e8-997f-93f79c18d5bc.png)

**Comment by JFrankfurt** [comment]
See #118 for a potential fix.

**Comment by dogada** [comment]
If Select is used as managed React component we should always provide an value to it but I'm not sure we should select for user first value from form's titleMap. IMO when user creates new object and haven't selected an value yet, we should show select's label instead of first value from titleMap, like it's done in Material UI exampes: https://material-ui.com/demos/selects/#simple-select

Same approach we can use for multi selects, i.e. don't select by default first value from titleMap and wait for user's decision.

Thoughts?

**Comment by stevehu** [comment]
@dogada You are right. We cannot assume that the first value is selected. If the select field is optional and the user is not going to select anything, they are forced to de-select it.

**Comment by dogada** [comment]
@stevehu, ok, so I will prepare a patch to fix initial value of select widgets.

**Comment by stevehu** [comment]
@JFrankfurt I think this has been fixed already. Could you please confirm and close the issue? Thanks.

**Comment by JFrankfurt** [comment]
closing because this is pretty stale - i don't know if it's still relevant, but I remember fixing it in a fork: https://github.com/TruSet/react-schema-form

**Comment by stevehu** [comment]
@JFrankfurt Thanks for your help. We have fully upgraded to the latest react and material-ui now and a lot of the components are rewritten.
