### ISSUE TITLE
Error: TextField.js:339 Uncaught TypeError: Cannot read property 'prepareStyles' of undefined

### ISSUE THREAD

**Issue by chiester** [networknt/react-schema-form#39]
Comes from~/react-schema-form/~/material-ui/TextField/TextField.js

Any idea how to resolve this?

**Comment by stevehu** [comment]
I would assume you are using the latest version which I will start with my investigation. Let me know if you are using different version. Thanks.

**Comment by chiester** [comment]
Yes. I'm using the latest. 

Thanks.

**Comment by stevehu** [comment]
The TextField is part of the material-ui and the latest version requires setup muitheme, otherwise some of the properties cannot be resolved. Take a look at ExamplePage.js and you can see how I setup muitheme.

Here are some useful links that might help.

https://github.com/callemall/material-ui/issues/5330

http://stackoverflow.com/questions/36953711/i-cannot-use-material-ui-components-after-update-to-material-ui0-15-0-beta-1

http://stackoverflow.com/questions/30717886/cannot-read-component-of-undefined-using-material-ui-with-browserify

**Comment by chiester** [comment]
Thanks @stevehu

**Comment by stevehu** [comment]
You are welcome. Happy coding.
